apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-srv
  labels:
    app: demo
spec:
  type: NodePort
  ports:
    - name: tcp1880
      protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 31800
    - name: udp2110
      protocol: UDP
      port: 2080
      targetPort: 2080
      nodePort: 32080
  selector:
    app: demo
